insert into dish (name, description, image) values ('Gerhold, Swaniawski and Kiehn', 'Chronic venous embolism and thrombosis of other thoracic veins', 'http://dummyimage.com/168x142.png/cc0000/ffffff');
insert into dish (name, description, image) values ('Hermiston and Sons', 'Acquired absence of cervix with remaining uterus', 'http://dummyimage.com/115x243.png/dddddd/000000');
insert into dish (name, description, image) values ('Stanton Inc', 'Heterophoria, unspecified', 'http://dummyimage.com/231x186.png/dddddd/000000');
insert into dish (name, description, image) values ('Carter, Legros and Wiza', 'Contact with and (suspected) exposure to other potentially hazardous chemicals', 'http://dummyimage.com/202x155.png/cc0000/ffffff');
insert into dish (name, description, image) values ('Jacobson-Breitenberg', 'Osteopathy resulting from poliomyelitis, pelvic region and thigh', 'http://dummyimage.com/238x143.png/dddddd/000000');
insert into dish (name, description, image) values ('Senger and Sons', 'Accident to powered aircraft, other and unspecified, injuring occupant of military aircraft, any', 'http://dummyimage.com/162x224.png/cc0000/ffffff');
insert into dish (name, description, image) values ('Pfannerstill, Durgan and Dare', 'Gangrene', 'http://dummyimage.com/151x248.png/ff4444/ffffff');
insert into dish (name, description, image) values ('Raynor-MacGyver', 'Hypertension secondary to renal disease, complicating pregnancy, childbirth, and the puerperium, antepartum condition or complication', 'http://dummyimage.com/188x230.png/ff4444/ffffff');
insert into dish (name, description, image) values ('Fay, Bartell and Purdy', 'Bipolar I disorder, most recent episode (or current) mixed, severe, without mention of psychotic behavior', 'http://dummyimage.com/241x110.png/5fa2dd/ffffff');
insert into dish (name, description, image) values ('Swift Group', 'Peroneal muscular atrophy', 'http://dummyimage.com/117x146.png/ff4444/ffffff');
insert into dish (name, description, image) values ('O''Conner LLC', 'Chronic venous hypertension with inflammation', 'http://dummyimage.com/126x177.png/dddddd/000000');
insert into dish (name, description, image) values ('Prohaska-Wuckert', 'Closed fracture of navicular [scaphoid], foot', 'http://dummyimage.com/115x123.png/ff4444/ffffff');
insert into dish (name, description, image) values ('Murazik-Bosco', 'Injury to cutaneous sensory nerve, upper limb', 'http://dummyimage.com/241x174.png/dddddd/000000');
insert into dish (name, description, image) values ('Conn LLC', 'Benign neoplasm of testis', 'http://dummyimage.com/107x199.png/ff4444/ffffff');
insert into dish (name, description, image) values ('VonRueden and Sons', 'Capsular contracture of breast implant', 'http://dummyimage.com/139x243.png/cc0000/ffffff');
insert into dish (name, description, image) values ('Bartell, Parisian and Greenholt', 'Unspecified obstetrical trauma, unspecified as to episode of care or not applicable', 'http://dummyimage.com/164x196.png/cc0000/ffffff');
insert into dish (name, description, image) values ('Bins-Moen', 'Screening for sickle-cell disease or trait', 'http://dummyimage.com/214x145.png/dddddd/000000');
insert into dish (name, description, image) values ('O''Connell-Lang', 'Digestive-genital tract fistula, female', 'http://dummyimage.com/175x109.png/dddddd/000000');
insert into dish (name, description, image) values ('Schmeler, Crona and Effertz', 'Other specified myoneural disorders', 'http://dummyimage.com/148x171.png/5fa2dd/ffffff');
insert into dish (name, description, image) values ('Mitchell-Ortiz', 'Trigeminal neuralgia', 'http://dummyimage.com/143x149.png/ff4444/ffffff');
