insert into reservation (description, NoP) values ('Unspecified injury of other blood vessels at ankle and foot level, unspecified leg, sequela', 1);
insert into reservation (description, NoP) values ('Unspecified dacryoadenitis, bilateral lacrimal glands', 2);
insert into reservation (description, NoP) values ('Unspecified open wound of toe without damage to nail', 3);
insert into reservation (description, NoP) values ('Other injury of other extensor muscle, fascia and tendon at forearm level, left arm, subsequent encounter', 4);
insert into reservation (description, NoP) values ('Pauciarticular juvenile rheumatoid arthritis, left elbow', 5);
insert into reservation (description, NoP) values ('Unspecified physeal fracture of right  metatarsal', 6);
insert into reservation (description, NoP) values ('Corrosion of second degree of unspecified hand, unspecified site, initial encounter', 7);
insert into reservation (description, NoP) values ('Toxic effect of venom of other Australian snake, undetermined, initial encounter', 8);
insert into reservation (description, NoP) values ('Post-traumatic osteoarthritis, unspecified hand', 9);
insert into reservation (description, NoP) values ('Unspecified open wound of abdominal wall, right lower quadrant with penetration into peritoneal cavity', 10);
insert into reservation (description, NoP) values ('Driver of bus injured in collision with car, pick-up truck or van in traffic accident, sequela', 11);
insert into reservation (description, NoP) values ('Burn of third degree of left knee, initial encounter', 12);
insert into reservation (description, NoP) values ('Partial traumatic amputation of left breast', 13);
insert into reservation (description, NoP) values ('Hemorrhagic detachment of retinal pigment epithelium, right eye', 14);
insert into reservation (description, NoP) values ('Injury of median nerve at upper arm level, right arm', 15);
insert into reservation (description, NoP) values ('Primary focal hyperhidrosis', 16);
insert into reservation (description, NoP) values ('Toxic effect of contact with stingray, undetermined, initial encounter', 17);
insert into reservation (description, NoP) values ('Other benign neoplasm of skin of lip', 18);
insert into reservation (description, NoP) values ('Idiopathic chronic gout, unspecified hand', 19);
insert into reservation (description, NoP) values ('Military operations involving accidental detonation of onboard marine weapons, military personnel, initial encounter', 20);
